### ISSUE TITLE
Missing artifact in pom.xml

### ISSUE THREAD

**Issue by klastereq** [zkoss-demo/zkspringmvc-demo#1]
Missing artifact org.zkoss.zkspringmvc:zkspringmvc:1.0-SNAPSHOT

**Comment by jumperchen** [comment]
Please use 1.0-SNAPSHOT-Eval instead

**Comment by klastereq** [comment]
Also missing

**Comment by jumperchen** [comment]
you have to put the ZK Eval repository, you can refer to the fixed commit
